export const DRINK_WHEEL_CHALLENGES: string[] = [
  "Drick 2 klunkar",
  "Drick 5 klunkar",
  "Drick 3 klunkar",
  "Drick 1 klunkar",
  "Ge bort 2 klunkar",
  "Ge bort 5 klunkar",
  "Ge bort 8 klunkar",
  "Ge bort 12 klunkar",
  "Ge bort 4 klunkar",
  "Alla med jeans dricker",
  "Du får byta plats med vem du vill - båda dricker",
  "Nästa gång du skrattar: drick",
  "Drick 1 klunk per syskon du har",
  "Välj två personer som måste skåla och dricka",
  "Du får immunity - slipp nästa straff",
  "Alla pekar på den som är mest full - den dricker",
  "Byt dryck med någon i rummet",
  "Alla tjejer dricker",
  "Alla killar dricker",
  "Du måste rimma med ett ord - missar du → drick 3",
  "Välj en person - om ni säger samma färg på 3 sekunder → du slipper dricka",
  "Alla som har A i sitt namn dricker",
  "Alla som har S i sitt namn dricker",
  "Alla som har E i sitt namn dricker",
  "Alla som har M i sitt namn dricker",
  "Drick om du har något svart på dig",
  "Välj en ny regel (t.ex. 'Ingen får säga ja')",
  "Alla håller upp sin dryck - sist dricker 2",
  "Välj någon att ge 1 klunk till - och drick 1 själv",
  "Välj någon att ge 2 klunk till - och drick 2 själv",
  "Välj någon att ge 4 klunk till - och drick 4 själv",
  "Vem är mest trolig att tappa bort sin telefon? Den dricker",
  "Om du har en app öppen i bakgrunden just nu - drick",
  "Gissa ett nummer mellan 1-5. Fel = drick 3",
  "Alla som har något blått på sig dricker",
  "Gör ett ljud - de andra härmar dig. Välj den sämsta → den dricker",
  "Ställ en 'Jag har aldrig' - de som gjort det dricker",
  "Du får ge bort 1 klunk till 3 olika personer",
  "Du får ge bort 5 klunk till 2 olika personer",
  "Du får ge bort 8 klunk till 2 olika personer",
  "Välj en 'partner in crime' - ni dricker tillsammans",
  "Vem ser mest nykter ut? Den personen dricker dubbelt resten av spelet 😅",
  "Visa senaste bilden i din kamera - eller drick 3",
  "Alla som har ett djur hemma dricker",
  "Välj någon att byta plats med - nya platser = ny energi",
  "Låt gruppen ställa en fråga till dig. Du måste svara - eller dricka",
  "Du är bartender! Häll upp till någon - båda dricker",
];
