export const DRINK_WHEEL_CHALLENGES: string[] = [
    "Drink 2 sips",
    "Drink 5 sips",
    "Drink 3 sips",
    "Drink 1 sip",
    "Give away 2 sips",
    "Give away 5 sips",
    "Give away 8 sips",
    "Give away 12 sips",
    "Give away 4 sips",
    "Everyone wearing jeans drinks",
    "You can switch places with anyone you want - both drink",
    "The next time you laugh: drink",
    "Drink 1 sip per sibling you have",
    "Choose two people who must toast and drink",
    "You get immunity - skip the next penalty",
    "Everyone points to the person who is most drunk - the person with the most votes drinks",
    "Swap drinks with someone in the room",
    "All girls drink",
    "All guys drink",
    "You must rhyme with a word - if you fail, drink 3",
    "Choose one person - if you say the same color, you both drink",
    "Choose one person - if you say the same number (1-5), you both drink",
    "Everyone who has 'A' in their name drinks",
    "Everyone who has 'S' in their name drinks",
    "Everyone who has 'E' in their name drinks",
    "Everyone who has 'M' in their name drinks",
    "Drink if you are wearing something black",
    "Choose a new rule (e.g., 'No one can say yes')",
    "Choose someone to give 1 sip to - and drink 1 yourself",
    "Choose someone to give 2 sips to - and drink 2 yourself",
    "Choose someone to give 4 sips to - and drink 4 yourself",
    "Who is most likely to lose their phone? That person drinks",
    "Everyone wearing something blue drinks",
    "Make a sound - the others imitate you. Choose the worst one, and that person drinks",
    "Ask a 'Never Have I Ever' question - those who have done it drink",
    "You can give away 1 sip to 3 different people",
    "You can give away 5 sips to 2 different people",
    "You can give away 8 sips to 2 different people",
    "Choose a 'partner in crime' - you drink together",
    "Who looks the most sober? That person drinks double for the rest of the game 😅",
    "Show the last picture in your camera - or drink 3",
    "Everyone who has a pet at home drinks",
    "Choose someone to switch places with - new places = new energy",
    "Let the group ask you a question. You must answer - or drink 8 sips",
    "You are the bartender! Pour a drink for someone - both drink",
];
