import { LocalChallengeConfig } from "@/types/local/challenge";

export default function ModeToChallenges(mode:LocalChallengeConfig["mode"]){
    switch(mode){
        case "normal":
            return DRINK_WHEEL_CHALLENGES;
        case "party":
            return DRINK_WHEEL_CHALLENGES_FOR_PARTY;
        case "sport":
            return DRINK_WHEEL_CHALLENGES_FOR_SPORTS;
        case "spicy":
            return DRINK_WHEEL_CHALLENGES_FOR_SPICY;
        default:{
            return []
        }
    }
}

const DRINK_WHEEL_CHALLENGES: string[] = [
    "Drick 2 klunkar",
    "Drick 5 klunkar",
    "Drick 3 klunkar",
    "Drick 1 klunk",
    "Ge bort 2 klunkar",
    "Ge bort 5 klunkar",
    "Ge bort 8 klunkar",
    "Ge bort 12 klunkar",
    "Ge bort 4 klunkar",
    "Alla som bär jeans dricker",
    "Du får byta plats med vem du vill – båda dricker",
    "Nästa gång du skrattar: drick",
    "Drick 1 klunk per syskon du har",
    "Välj två personer som måste skåla och dricka",
    "Du får immunitet – hoppa över nästa straff",
    "Alla pekar på den som är mest full – den med flest röster dricker",
    "Byt drink med någon i rummet",
    "Alla tjejer dricker",
    "Alla killar dricker",
    "Du måste rimma på ett ord – om du misslyckas, drick 3",
    "Välj en person – om ni säger samma färg, dricker ni båda",
    "Välj en person – om ni säger samma nummer (1-5), dricker ni båda",
    "Alla som har 'A' i sitt namn dricker",
    "Alla som har 'S' i sitt namn dricker",
    "Alla som har 'E' i sitt namn dricker",
    "Alla som har 'M' i sitt namn dricker",
    "Drick om du har på dig något svart",
    "Välj en ny regel (t.ex. 'Ingen får säga ja')",
    "Välj någon att ge 1 klunk till – och drick 1 själv",
    "Välj någon att ge 2 klunkar till – och drick 2 själv",
    "Välj någon att ge 4 klunkar till – och drick 4 själv",
    "Vem tappar bort sin telefon mest sannolikt? Den personen dricker",
    "Alla som har på sig något blått dricker",
    "Gör ett ljud – de andra imiterar dig. Välj den sämsta, den personen dricker",
    "Ställ en 'Har aldrig'-fråga – de som har gjort det dricker",
    "Du får ge bort 1 klunk till 3 olika personer",
    "Du får ge bort 5 klunkar till 2 olika personer",
    "Du får ge bort 8 klunkar till 2 olika personer",
    "Välj en 'brottspartner' – ni dricker tillsammans",
    "Vem ser mest nykter ut? Den personen dricker dubbelt resten av spelet 😅",
    "Visa den sista bilden i din kamera – eller drick 3",
    "Alla som har ett husdjur hemma dricker",
    "Välj någon att byta plats med – nya platser = ny energi",
    "Låt gruppen ställa en fråga till dig. Du måste svara – annars drick 8 klunkar",
    "Du är bartendern! Häll upp en drink åt någon – båda dricker",
];

const DRINK_WHEEL_CHALLENGES_FOR_PARTY: string[] = [
  "Ställ någon en fråga som kan göra dem obekväma – de måste svara sanningsenligt, annars drick 3",
  "Välj någon att ha en minidebatt med – förloraren dricker",
  "Berätta en kontroversiell åsikt. Om någon inte håller med, dricker de",
  "Alla pekar på någon de tycker är den mest 'tråkiga' – den personen dricker",
  "Välj en person och berätta för dem vad de gör fel i livet just nu – de dricker om de inte argumenterar emot",
  "Vem tror du är mest sannolik att starta ett gräl ikväll? Den personen dricker",
  "Be någon avslöja sin största hemlighet – om de inte gör det, drick 5",
  "Du har 30 sekunder på dig att ge din bästa förolämpning. Om den inte träffar, drick",
  "Starta ett gräl med någon. Den första som ger sig dricker 4",
  "Hitta någon som inte håller med om din åsikt om något viktigt – ni båda dricker",
  "Vem tycker du skulle vara den värsta personen att bo med? De dricker",
  "Välj någon som ska ge dig en utmaning. Om de vägrar, drick 3",
  "Någon måste berätta sitt mest pinsamma ögonblick – om det inte är pinsamt nog, dricker de",
  "Alla som någon gång har ghostat någon i ett förhållande dricker",
  "Välj någon att göra sin bästa imitation av dig. Om den är dålig, dricker de 2",
  "Vem är mest sannolik att hamna i ett slagsmål ikväll? Den personen dricker",
  "Starta ett gräl om något trivialt. Den som ger sig först dricker 5",
  "Gör en anklagelse mot någon i rummet. Om de inte kan försvara sig tillräckligt bra, dricker de",
  "Alla pekar på den person de litar minst på. Den personen dricker",
  "Berätta en lögn om dig själv. Om ingen avslöjar dig, drick",
  "Alla som någon gång har fuskat i ett spel dricker",
  "Välj någon att byta drinkar med, men dela först med er av något pinsamt om varandra",
  "Fråga någon deras minst omtyckta sak med dig. Om de svarar, drick 4",
  "Hitta på en löjlig utmaning som någon ska göra. Om de vägrar, drick 3",
  "Du måste berätta för gruppen en sak du alltid har hatat med dina vänner – annars drick 5",
  "Vem är den minst pålitliga personen här? Den personen dricker dubbelt nästa tur",
  "Välj någon att argumentera med i 30 sekunder om något fånigt. Den som är högljuddast dricker",
  "Någon måste ge dig en komplimang. Om den inte är uppriktig, dricker de",
  "Välj någon att vara din 'fiende' resten av spelet – ni dricker båda varje gång den andra gör det",
  "Alla som någon gång har grälat om småsaker dricker",
  "Fråga personen till vänster om dig vad de tycker är din värsta egenskap. Om det svider, drick 3",
  "Gör en obekväm förutsägelse om någons framtid. Om den är fel, drick",
  "Alla röstar på vem som är mest sannolik att hamna i trubbel ikväll. Vinnaren dricker",
  "Vem är mest sannolik att lämna tidigt? Den personen dricker",
  "Ge en spelare en utmaning de inte kan slutföra. Om de misslyckas, dricker de",
  "Vem här har de mest pinsamma inläggen på sociala medier? Den personen dricker",
  "Välj någon att avslöja en kontroversiell åsikt, annars dricker de",
  "Välj två personer att argumentera. Om ingen ger sig, dricker båda",
  "Be någon att göra en utmaning du väljer. Om de vägrar, drick",
  "Välj någon och övertyga dem att göra något löjligt. Om de vägrar, dricker de",
  "Vem här tycker du skulle vara den sämsta ledaren? Den personen dricker",
  "Välj någon att förklara varför de förtjänar att vinna det här spelet. Om det inte är övertygande, dricker de",
  "Starta en 'Skulle du hellre?'-lek med gruppen. Den som får det sämsta svaret dricker",
  "Alla som någon gång har grälat om matpreferenser dricker",
  "Välj någon att göra det mest löjliga ansiktet de kan. Om du skrattar, dricker du",
  "Vem här skulle vara svårast att komma överens med i en gruppchatt? Den personen dricker",
  "Alla som någon gång har grälat offentligt dricker",
  "Välj någon att dela med sig av en nyligen kontroversiell konversation de haft – om de inte gör det, dricker de",
  "Fråga någon vem de tror ljuger mest ikväll. Om de inte nämner ett namn, drick 4",
  "Välj någon att be om ursäkt för något de har gjort ikväll, annars dricker de 3"
];

const DRINK_WHEEL_CHALLENGES_FOR_SPORTS: string[] = [
  "Gör 10 jumping jacks. Om du slutar för tidigt, drick 3",
  "Gör din bästa dansrörelse i 30 sekunder. Om du ser klumpig ut, drick",
  "Spring på stället i 1 minut. Om du stannar, drick 4",
  "Välj någon att tävla med över rummet. Förloraren dricker",
  "Gör 5 armhävningar. Om du misslyckas, drick 3",
  "Snurra runt 10 gånger och försök att gå rakt. Om du ramlar, drick 5",
  "Hoppa på ett ben i 1 minut. Om du ramlar eller stannar, drick",
  "Hitta ett slumpmässigt föremål i rummet och gör det till din 'danspartner' i 30 sekunder. Om du inte är engagerad, drick 4",
  "Gör 10 knäböj. Om du inte kan slutföra dem, drick 3",
  "Välj någon som ska göra 5 armhävningar. Om de inte kan göra dem, dricker ni båda",
  "Försök att göra en rondat. Om du misslyckas, drick 5",
  "Gör din bästa imitation av en bodybuilder som flexar i 30 sekunder. Om du bryter karaktären, drick",
  "Gör 20 situps. Om du slutar för tidigt, drick 3",
  "Välj någon att utmana dig till en tävling runt rummet. Om du förlorar, dricker ni båda",
  "Gör en planka i 30 sekunder. Om du misslyckas, drick 4",
  "Agera ut en yogaställning. Om den inte är övertygande, drick 3",
  "Välj någon att brottas med i 1 minut. Förloraren dricker",
  "Gör 10 burpees. Om du misslyckas, drick 4",
  "Ta ett löphopp och försök att landa utan att falla. Om du ramlar, drick 3",
  "Gör din bästa imitation av en kyckling i 30 sekunder. Om den inte är rolig, drick 4",
  "Balansera en bok på huvudet och gå över rummet. Om den faller, drick 3",
  "Hitta något att använda som hopprep. Hoppa i 1 minut. Om du stannar, drick 3",
  "Försök att göra en handstående. Om du misslyckas, drick 5",
  "Välj någon som ska bära dig på ryggen (piggyback ride) i 1 minut. Om de tappar dig, dricker de 4",
  "Gör en väggsitt i 1 minut. Om du faller, drick 4",
  "Välj en punkt på väggen. Stirra på den medan du snurrar runt 10 gånger, försök sedan att gå rakt. Om du snubblar, drick 4",
  "Gör masken. Om du inte kan göra det, drick 5",
  "Välj någon att armbrottas med. Om du förlorar, dricker ni båda",
  "Gör 5 armhävningar med fötterna på en stol. Om du inte kan, drick 4",
  "Välj någon att tävla med i en high-five-tävling. Den vars high-five blir avvisad dricker",
  "Agera ut ditt favoritidrottsdrag i 30 sekunder. Om ingen gissar det, drick 4",
  "Försök att göra en bakåtvolt (eller något trick du är säker på att du klarar). Om du misslyckas, drick 5",
  "Hitta ett föremål i rummet och använd det som rekvisita för en rolig sketch. Om den inte är rolig, dricker du",
  "Gör 10 utfall. Om du inte kan slutföra dem, drick 3",
  "Gå runt i rummet med en sked på näsan. Om den faller, drick 3",
  "Gör 15 jumping jacks, men varje gång du hoppar måste du ropa 'party!' Om du glömmer, drick 3",
  "Hitta en partner och ge varandra en piggyback ride. Om någon av er tappar den andra, dricker båda 4",
  "Välj någon att tävla med i en löptävling där ni måste gå konstigt (baklänges, sidledes, etc.). Om du förlorar, dricker du",
  "Håll en plankposition och ta en klunk var 10:e sekund du kan hålla den. Om du faller, drick 3",
  "Balansera ett glas vatten på huvudet medan du går över rummet. Om det spills, drick 4",
  "Välj någon som ska försöka härma dina dansrörelser. Om de misslyckas, dricker de 4",
  "Gör en konstig och knasig dans i 1 minut. Om ingen skrattar, drick 3",
  "Utmana någon till en stirrtävling. Förloraren dricker 4",
  "Gör 10 luftknäböj. Om du slutar för tidigt, drick 4",
  "Hitta på din bästa hemliga handskakning med någon. Om den inte är smidig, drick 3",
  "Välj någon att göra en skottkärra-tävling med dig. Om du förlorar, dricker ni båda 4",
  "Välj någon att ha en fånig gångtävling med. Om de vinner, drick 3",
  "Gör hokey pokey med gruppen. Om du klantar dig, drick 4",
  "Låtsas vara en staty i 1 minut. Om du rör dig, drick 3",
  "Hitta ett slumpmässigt föremål i rummet och använd det som mikrofon för att sjunga i 30 sekunder. Om det är hemskt, drick 4",
  "Gör 5 armhävningar med en hand. Om du misslyckas, drick 5",
  "Välj någon att hålla en planka med dig i 30 sekunder. Om någon av er faller, dricker båda 4",
  "Agera som ett djur du väljer i 1 minut. Om du bryter karaktären, drick 4",
  "Hitta något att balansera på huvudet och gå över rummet. Om det faller, drick 4",
  "Utmana någon till en 'vem kan hålla andan längst'-tävling. Förloraren dricker 4"
];

const DRINK_WHEEL_CHALLENGES_FOR_SPICY: string[] = [
  "Sms:a ditt ex 'Jag saknar dig' – om de svarar, drick. Om de inte gör det, sms:a 'Jag ångrar allt' och ta 2 drinkar.",
  "Skicka ett vågat DM till din crush – om de svarar, drick. Om de inte gör det, är du skyldig dem en komplimang personligen.",
  "Välj någon att avslöja sin mest pinsamma hemlighet. Om de vägrar, drick 3.",
  "Berätta för gruppen din mest pinsamma raggningshistoria. Om den inte är tillräckligt dålig, drick 4.",
  "Välj någon att sms:a sitt ex och säga 'Vi borde ses snart.' Om de vägrar, drick 5.",
  "Fråga gruppen vem som har sämst musiksmak här. Den personen dricker.",
  "Skicka ett flörtigt sms till någon i gruppen. Om de inte svarar inom 5 minuter, drick 3.",
  "Välj någon att dela sitt mest pinsamma inlägg på sociala medier. Om de vägrar, drick 4.",
  "Gör din bästa imitation av någon i rummet – om de gissar rätt, drick. Om inte, drick 3.",
  "Ring någon i dina kontakter och säg: 'Jag tänkte just på dig.' Om de inte svarar, sms:a dem 'Jag saknar dig' och drick 2.",
  "Välj någon att berätta för gruppen sin mest pinsamma första dejt-historia. Om de vägrar, drick 4.",
  "Välj någon att erkänna sin största rädsla. Om de vägrar, dricker ni båda 3.",
  "Välj någon och be dem avslöja sitt mest pinsamma fylle-ögonblick. Om de vägrar, drick 5.",
  "Fråga någon vad deras största 'deal-breaker' är i dejting. Om de vägrar, drick 3.",
  "Skicka ett 'tänker på dig'-sms till någon du har ghostat. Om de svarar, drick. Om inte, drick 2.",
  "Välj någon att avslöja det mest pinsamma de har gjort för att imponera på någon. Om de vägrar, drick 4.",
  "Fråga gruppen vem som är mest sannolik att bli påkommen med att skicka ett fylle-sms. Den personen dricker.",
  "Berätta för gruppen det mest pinsamma du har googlat. Om det inte är pinsamt nog, drick 5.",
  "Välj någon att erkänna sitt senaste pinsamma ögonblick. Om de vägrar, drick 4.",
  "Ring din mamma och berätta för henne att du är kär i någon i rummet. Om hon inte svarar, drick 2.",
  "Be någon att sms:a sin crush och säga 'Jag kan inte sluta tänka på dig.' Om de vägrar, drick 3.",
  "Välj någon att avslöja det mest pinsamma som har hänt dem på jobbet. Om de vägrar, drick 4.",
  "Berätta för gruppen om senaste gången du skickade ett vågat eller pinsamt sms. Om det inte är tillräckligt saftigt, drick 5.",
  "Välj någon och be dem sms:a sitt ex och säga 'Vi måste prata snart.' Om de vägrar, drick 3.",
  "Vem är mest sannolik att bli kär i fel person? Den personen dricker.",
  "Välj någon att erkänna senaste gången de ljög för någon. Om de vägrar, drick 4.",
  "Välj någon att dela sin mest pinsamma barndomsminne. Om de vägrar, drick 3.",
  "Välj någon att skicka en vågad eller kontroversiell tweet. Om den blir raderad, dricker de 5.",
  "Sms:a din crush och fråga ut dem. Om de säger nej, dricker ni båda 4.",
  "Välj någon och be dem skicka ett 'Jag saknar dig'-sms till sitt ex. Om de vägrar, drick 5.",
  "Berätta för gruppen det mest pinsamma du har gjort offentligt. Om det inte är pinsamt nog, drick 6.",
  "Välj någon att erkänna för gruppen sin största dejtingånger. Om de vägrar, drick 4.",
  "Välj någon att sms:a sin vän och säga 'Vi måste prata.' Om de vägrar, drick 3.",
  "Fråga gruppen vem som har den mest pinsamma raggningshistorian. Den med flest röster dricker.",
  "Välj någon att ringa sitt ex och fråga: 'Träffar du någon annan?' Om de vägrar, drick 5.",
  "Berätta för gruppen något du aldrig har berättat för någon. Om det inte är vilt nog, drick 6.",
  "Välj någon att sms:a sitt ex och säga 'Jag saknar de gamla tiderna.' Om de vägrar, drick 4.",
  "Fråga gruppen vem som är mest sannolik att falla för en dålig raggningsreplik. Den personen dricker.",
  "Välj någon att skicka ett röstmeddelande till sin crush och säga 'Jag kan inte sluta tänka på dig.' Om de vägrar, drick 5.",
  "Berätta för gruppen om ditt mest pinsamma ögonblick i ett förhållande. Om det inte är pinsamt nog, drick 4.",
  "Välj någon att dela sin mest pinsamma sms-konversation med dig. Om de vägrar, drick 3.",
  "Skicka ett 'tänker på dig'-meddelande till den sista personen du sms:ade. Om de svarar är du fri. Om inte, drick 3.",
  "Välj någon att avslöja sitt mest pinsamma ögonblick inför sina föräldrar. Om de vägrar, drick 4.",
  "Välj någon att erkänna sin största ånger i ett förhållande. Om de vägrar, drick 5.",
  "Berätta för gruppen senaste gången du ghostade någon. Om det inte är tillräckligt saftigt, drick 5.",
  "Fråga någon vem deras första kyss var med. Om de vägrar, drick 4.",
  "Välj någon att sms:a sin nuvarande partner och säga: 'Jag tänker på dig just nu.' Om de vägrar, drick 3.",
  "Skicka ett röstmeddelande till din crush och säg 'Jag har tänkt på dig hela dagen.' Om de svarar är du fri. Om inte, drick 5.",
  "Välj någon att skicka ett 'Jag saknar dig'-sms till sitt ex. Om de vägrar, drick 4.",
  "Be någon att avslöja sin mest pinsamma hemlighet om sitt kärleksliv. Om de vägrar, drick 5.",
  "Berätta för gruppen det mest pinsamma du har gjort när du försökte imponera på någon. Om det inte är tillräckligt dåligt, drick 6."
];
