import { LocalChallengeConfig } from "@/types/local/challenge";

export default function ModeToChallenges(mode:LocalChallengeConfig["mode"]){
    switch(mode){
        case "normal":
            return DRINK_WHEEL_CHALLENGES;
        case "party":
            return DRINK_WHEEL_CHALLENGES_FOR_PARTY;
        case "sport":
            return DRINK_WHEEL_CHALLENGES_FOR_SPORTS;
        case "spicy":
            return DRINK_WHEEL_CHALLENGES_FOR_SPICY;
        default:{
            return []
        }
    }
}

const DRINK_WHEEL_CHALLENGES: string[] = [
    "Drink 2 sips",
    "Drink 5 sips",
    "Drink 3 sips",
    "Drink 1 sip",
    "Give away 2 sips",
    "Give away 5 sips",
    "Give away 8 sips",
    "Give away 12 sips",
    "Give away 4 sips",
    "Everyone wearing jeans drinks",
    "You can switch places with anyone you want - both drink",
    "The next time you laugh: drink",
    "Drink 1 sip per sibling you have",
    "Choose two people who must toast and drink",
    "You get immunity - skip the next penalty",
    "Everyone points to the person who is most drunk - the person with the most votes drinks",
    "Swap drinks with someone in the room",
    "All girls drink",
    "All guys drink",
    "You must rhyme with a word - if you fail, drink 3",
    "Choose one person - if you say the same color, you both drink",
    "Choose one person - if you say the same number (1-5), you both drink",
    "Everyone who has 'A' in their name drinks",
    "Everyone who has 'S' in their name drinks",
    "Everyone who has 'E' in their name drinks",
    "Everyone who has 'M' in their name drinks",
    "Drink if you are wearing something black",
    "Choose a new rule (e.g., 'No one can say yes')",
    "Choose someone to give 1 sip to - and drink 1 yourself",
    "Choose someone to give 2 sips to - and drink 2 yourself",
    "Choose someone to give 4 sips to - and drink 4 yourself",
    "Who is most likely to lose their phone? That person drinks",
    "Everyone wearing something blue drinks",
    "Make a sound - the others imitate you. Choose the worst one, and that person drinks",
    "Ask a 'Never Have I Ever' question - those who have done it drink",
    "You can give away 1 sip to 3 different people",
    "You can give away 5 sips to 2 different people",
    "You can give away 8 sips to 2 different people",
    "Choose a 'partner in crime' - you drink together",
    "Who looks the most sober? That person drinks double for the rest of the game 😅",
    "Show the last picture in your camera - or drink 3",
    "Everyone who has a pet at home drinks",
    "Choose someone to switch places with - new places = new energy",
    "Let the group ask you a question. You must answer - or drink 8 sips",
    "You are the bartender! Pour a drink for someone - both drink",
];

const DRINK_WHEEL_CHALLENGES_FOR_PARTY: string[] = [
  "Ask someone a question that might make them uncomfortable - they must answer truthfully, or drink 3",
  "Choose someone to have a mini debate with - loser drinks",
  "Tell a controversial opinion. If anyone disagrees, they drink",
  "Everyone points to someone they think is the most 'boring' - that person drinks",
  "Pick a person and tell them what they’re doing wrong in life right now - they drink if they don’t argue back",
  "Who do you think is most likely to start an argument tonight? That person drinks",
  "Ask someone to reveal their biggest secret - if they don’t, they drink 5",
  "You have 30 seconds to give your best insult. If it doesn’t land, drink",
  "Start an argument with someone. First person to back down drinks 4",
  "Find someone who disagrees with your opinion on something major - you both drink",
  "Who do you think would be the worst person to live with? They drink",
  "Pick someone to give you a dare. If they refuse, they drink 3",
  "Someone has to tell you their most embarrassing moment - if it’s not embarrassing enough, they drink",
  "Everyone who has ever ghosted someone in a relationship drinks",
  "Pick someone to do their best impression of you. If it’s bad, they drink 2",
  "Who’s the most likely to get into a fight tonight? That person drinks",
  "Start an argument about something trivial. Whoever gives in first drinks 5",
  "Make an accusation about someone in the room. If they can’t defend themselves well enough, they drink",
  "Everyone points at the person they trust the least. That person drinks",
  "Tell a lie about yourself. If no one calls you out, drink",
  "Everyone who has ever cheated in a game drinks",
  "Pick someone to swap drinks with, but first, share something embarrassing about each other",
  "Ask someone their least favorite thing about you. If they answer, they drink 4",
  "Make a ridiculous challenge for someone to do. If they refuse, they drink 3",
  "You have to tell the group one thing you’ve always hated about your friends - or drink 5",
  "Who is the least trustworthy person here? That person drinks double next turn",
  "Choose someone to argue with for 30 seconds about something silly. The louder one drinks",
  "Someone has to give you a compliment. If it’s not sincere, they drink",
  "Pick someone to be your 'enemy' for the rest of the game - you both drink every time the other does",
  "Everyone who has ever had an argument over something petty drinks",
  "Ask the person to your left what they think is your worst trait. If it stings, they drink 3",
  "Make an uncomfortable prediction about someone’s future. If it’s wrong, drink",
  "Everyone votes for who is most likely to get into trouble tonight. The winner drinks",
  "Who’s most likely to leave early? That person drinks",
  "Give a player a challenge they can’t complete. If they fail, they drink",
  "Who here has the most embarrassing social media posts? That person drinks",
  "Pick someone to reveal a controversial opinion, or they drink",
  "Choose two people to argue. If neither backs down, both drink",
  "Ask someone to do a dare of your choosing. If they refuse, they drink",
  "Pick someone and convince them to do something ridiculous. If they refuse, they drink",
  "Who do you think here would make the worst leader? That person drinks",
  "Choose someone to explain why they deserve to win this game. If it’s not convincing, they drink",
  "Start a game of 'Would You Rather?' with the group. The person who gets the worst answer drinks",
  "Everyone who has ever argued about food preferences drinks",
  "Pick someone to make the most ridiculous face they can. If you laugh, you drink",
  "Who here would be the hardest to get along with in a group chat? That person drinks",
  "Everyone who’s ever had a public argument drinks",
  "Choose someone to share a recent controversial conversation they had - if they don’t, they drink",
  "Ask someone who they think is lying the most tonight. If they don’t give a name, they drink 4",
  "Pick someone to apologize for something they’ve done tonight, or they drink 3"
];


const DRINK_WHEEL_CHALLENGES_FOR_SPORTS: string[] = [
  "Do 10 jumping jacks. If you stop early, drink 3",
  "Do your best dance move for 30 seconds. If you look awkward, drink",
  "Run in place for 1 minute. If you stop, drink 4",
  "Pick someone to race across the room with. The loser drinks",
  "Do 5 push-ups. If you fail, drink 3",
  "Spin around 10 times and try to walk in a straight line. If you fall, drink 5",
  "Hop on one foot for 1 minute. If you fall or stop, drink",
  "Find a random object in the room and make it your 'dance partner' for 30 seconds. If you’re not committed, drink 4",
  "Do 10 squats. If you can’t finish them, drink 3",
  "Choose someone to do 5 push-ups. If they can’t do them, you both drink",
  "Try to do a cartwheel. If you fail, drink 5",
  "Do your best impression of a bodybuilder flexing for 30 seconds. If you break character, drink",
  "Do 20 sit-ups. If you stop early, drink 3",
  "Pick someone to challenge you to a race around the room. If you lose, you both drink",
  "Do a plank for 30 seconds. If you fail, drink 4",
  "Act out a yoga pose. If it’s not convincing, drink 3",
  "Pick someone to wrestle with for 1 minute. Loser drinks",
  "Do 10 burpees. If you fail, drink 4",
  "Take a running jump and try to land without falling. If you fall, drink 3",
  "Do your best impression of a chicken for 30 seconds. If it’s not funny, drink 4",
  "Balance a book on your head and walk across the room. If it falls, drink 3",
  "Find something to use as a skipping rope. Skip for 1 minute. If you stop, drink 3",
  "Try to do a handstand. If you fail, drink 5",
  "Pick someone to give you a piggyback ride for 1 minute. If they drop you, they drink 4",
  "Do a wall sit for 1 minute. If you fall, drink 4",
  "Pick a spot on the wall. Stare at it while spinning around 10 times, then try to walk in a straight line. If you stumble, drink 4",
  "Do the worm. If you can’t do it, drink 5",
  "Choose someone to arm wrestle with. If you lose, you both drink",
  "Do 5 push-ups with your feet on a chair. If you can’t, drink 4",
  "Pick someone to do a high-five contest with. Whoever’s high-five gets rejected, drinks",
  "Act out your favorite sports move for 30 seconds. If no one guesses it, drink 4",
  "Try to do a backflip (or any trick you're confident you can do). If you fail, drink 5",
  "Find an object in the room and use it as a prop for a funny skit. If it’s not funny, you drink",
  "Do 10 lunges. If you can’t finish them, drink 3",
  "Walk around the room with a spoon on your nose. If it falls, drink 3",
  "Do 15 jumping jacks, but every time you jump, you have to shout 'party!' If you forget, drink 3",
  "Find a partner and give each other a piggyback ride. If one of you drops, both drink 4",
  "Pick someone to have a race where you have to do a weird walk (backwards, sideways, etc.). If you lose, you drink",
  "Hold a plank position and take a sip every 10 seconds you can hold it. If you fall, drink 3",
  "Balance a glass of water on your head while walking across the room. If it spills, drink 4",
  "Pick someone to try to mimic your dance moves. If they fail, they drink 4",
  "Do a weird and wacky dance for 1 minute. If no one laughs, drink 3",
  "Challenge someone to a staring contest. Loser drinks 4",
  "Do 10 air squats. If you stop early, drink 4",
  "Create your best secret handshake with someone. If it’s not smooth, drink 3",
  "Pick someone to do a wheelbarrow race with you. If you lose, both drink 4",
  "Pick someone to do a silly walk competition with. If they beat you, drink 3",
  "Do the hokey pokey with the group. If you mess it up, drink 4",
  "Pretend to be a statue for 1 minute. If you move, drink 3",
  "Find a random item in the room and use it as a microphone to sing for 30 seconds. If it’s terrible, drink 4",
  "Do 5 push-ups with one hand. If you fail, drink 5",
  "Pick someone to hold a plank with you for 30 seconds. If either of you falls, both drink 4",
  "Act like an animal of your choice for 1 minute. If you break character, drink 4",
  "Find something to balance on your head and walk across the room. If it falls, drink 4",
  "Challenge someone to a 'who can hold their breath the longest' contest. The loser drinks 4"
];

const DRINK_WHEEL_CHALLENGES_FOR_SPICY: string[] = [
  "Text your ex 'I miss you' — if they reply, drink. If they don’t, text them 'I regret everything' and take 2 drinks.",
  "Send a risky DM to your crush — if they respond, drink. If they don't, you owe them a compliment in person.",
  "Pick someone to reveal their most embarrassing secret. If they refuse, drink 3.",
  "Tell the group your most awkward hookup story. If it’s not bad enough, drink 4.",
  "Pick someone to text their ex saying 'We should catch up soon.' If they refuse, drink 5.",
  "Ask the group who here has the worst taste in music. That person drinks.",
  "Send a flirty text to someone in the group. If they don’t reply within 5 minutes, drink 3.",
  "Pick someone to share their most embarrassing social media post. If they refuse, drink 4.",
  "Do your best impression of someone in the room — if they guess it right, drink. If not, drink 3.",
  "Call someone in your contacts and say, 'I was just thinking about you.' If they don’t pick up, text them, 'I miss you' and drink 2.",
  "Pick someone to tell the group their most awkward first date story. If they refuse, drink 4.",
  "Choose someone to confess their biggest fear. If they refuse, you both drink 3.",
  "Pick someone and make them reveal their most embarrassing drunk moment. If they refuse, drink 5.",
  "Ask someone what their biggest dating deal-breaker is. If they refuse, drink 3.",
  "Send a ‘thinking of you’ text to someone you’ve ghosted. If they reply, drink. If not, drink 2.",
  "Pick someone to reveal the most awkward thing they’ve done to impress someone. If they refuse, drink 4.",
  "Ask the group who’s most likely to get caught sending a drunk text. That person drinks.",
  "Tell the group the most embarrassing thing you’ve Googled. If it’s not embarrassing enough, drink 5.",
  "Pick someone to admit their most recent embarrassing moment. If they refuse, drink 4.",
  "Call your mom and tell her you’re in love with someone in the room. If she doesn’t pick up, drink 2.",
  "Ask someone to text their crush and say 'I can’t stop thinking about you.' If they refuse, drink 3.",
  "Pick someone to reveal the most awkward thing that’s happened to them at work. If they refuse, drink 4.",
  "Tell the group about the last time you sent a risky or embarrassing text. If it’s not juicy enough, drink 5.",
  "Pick someone and make them text their ex saying ‘We need to talk soon.’ If they refuse, drink 3.",
  "Who’s the most likely to fall in love with the wrong person? That person drinks.",
  "Pick someone to admit the last time they lied to someone. If they refuse, drink 4.",
  "Choose someone to share their most embarrassing childhood memory. If they refuse, drink 3.",
  "Pick someone to send a risky or controversial tweet. If it gets deleted, they drink 5.",
  "Text your crush and ask them out. If they say no, you both drink 4.",
  "Pick someone and make them send a 'I miss you' text to their ex. If they refuse, drink 5.",
  "Tell the group the most embarrassing thing you've done in public. If it’s not embarrassing enough, drink 6.",
  "Choose someone to admit to the group their biggest dating regret. If they refuse, drink 4.",
  "Pick someone to text their friend saying ‘We need to talk.’ If they refuse, drink 3.",
  "Ask the group who has the most embarrassing hookup story. The person with the most votes drinks.",
  "Pick someone to call their ex and ask them, 'Are you seeing anyone else?' If they refuse, drink 5.",
  "Tell the group something you've never told anyone. If it’s not wild enough, drink 6.",
  "Pick someone to text their ex saying 'I miss the good times.' If they refuse, drink 4.",
  "Ask the group who is most likely to fall for a bad pickup line. That person drinks.",
  "Pick someone to send a voice memo to their crush saying 'I can’t stop thinking about you.' If they refuse, drink 5.",
  "Tell the group about your most awkward moment in a relationship. If it’s not embarrassing enough, drink 4.",
  "Pick someone to share their most awkward text exchange with you. If they refuse, drink 3.",
  "Send a 'thinking of you' message to the last person you texted. If they reply, you’re free. If not, drink 3.",
  "Pick someone to reveal their most embarrassing moment in front of their parents. If they refuse, drink 4.",
  "Choose someone to admit their biggest regret in a relationship. If they refuse, drink 5.",
  "Tell the group the last time you ghosted someone. If it’s not juicy enough, drink 5.",
  "Ask someone who their first kiss was with. If they refuse, drink 4.",
  "Pick someone to text their current partner saying, 'I’m thinking of you right now.' If they refuse, drink 3.",
  "Send a voice note to your crush saying 'I’ve been thinking about you all day.' If they reply, you’re free. If not, drink 5.",
  "Pick someone to send a 'I miss you' text to their ex. If they refuse, drink 4.",
  "Ask someone to reveal their most embarrassing secret about their love life. If they refuse, drink 5.",
  "Tell the group the most awkward thing you’ve done while trying to impress someone. If it’s not bad enough, drink 6."
];

