import { PeklekTypes } from "@/types/local/peklek";

export const PeklekTypeToChallenges = (type: typeof PeklekTypes[number]) => {
    switch (type) {
        case "normal":
            return PEKLEK_NORMAL
        case "spicy":
            return PEKLEK_SPICY
        default:
            return []
    }
}

export const PEKLEK_NORMAL = [
    "Mest benägen att bli kär vid första ögonkastet?",
    "Mest trolig att skicka pinsamt SMS till fel person?",
    "Mest trolig att bli kär i sin bästa väns partner?",
    "Skulle kunna kyssa en främling på en fest?",
    "Sannolikt prova på speed dating?",
    "Mest trolig att ha en hemlig beundrare?",
    "Mest trolig att gå på blinddejt arrangerad av vän?",
    "Skulle flirta med polis för att slippa böter?",
    "Mest trolig att bli 'ghostad' efter dejt?",
    "Skulle säga 'jag älskar dig' först?",
    "Mest trolig att spela 'truth or dare' på första dejt?",
    "Mest trolig att ha en krånglig kärlekstriangel?",
    "Mest trolig att glömma namnet på dejt?",
    "Har en hemlig crush på kollega?",
    "Går på flest Tinderdejter på en vecka?",
    "Blir upprörd om ex dejtar ny person?",
    "Mest trolig att ha en online-romans?",
    "Mest trolig att bli kär på semestern?",
    "Skulle kunna delta i reality-TV om dejting?",
    "Mest trolig att dejt slutar i arresten?",
    "Mest trolig att skaffa matchande tatuering med partner?",
    "Mest trolig att prova online dejting?",
    "Skulle kunna bli förälskad i någons röst?",
    "Mest trolig att hålla handen på första dejten?",
    "Mest trolig att ta med vän på dejt som backup?",
    "Har rest till flest länder?",
    "Har vunnit flest idrottsutmärkelser?",
    "Har bestigit det högsta berget?",
    "Har läst flest böcker?",
    "Spelar mest TV- eller datorspel?",
    "Har det svåraste jobbet?",
    "Dricker mest kaffe?",
    "Har mest pengar?",
    "Har det värsta jobbet?",
    "Har högst IQ?",
    "Är lyckligast?",
    "Mest sannolik att starta framgångsrikt företag?",
    "Är mest händig?",
    "Är roligast?",
    "Skulle överleva längst på öde ö?",
    "Kommer att leva längst?",
    "Kommer bli fullast ikväll?",
    "Är yngst?",
    "Är lugnast?",
    "Har det bästa jobbet?",
    "Spenderar mest tid på telefonen?",
    "Skulle kunna vinna på lotto men förlora lotten?",
    "Har bäst chans i en zombieapokalyps?",
    "Har gjort en plastikoperation?",
    "Pratar först och tänker sen?",
    "Vill helst flytta till Mars?",
    "Skulle kunna glömma vart de parkerat bilen?",
    "Är mest trolig att bli politiker?",
    "Faller oftast i skidliften?",
    "Skulle kunna delta i Paradise Hotel?",
    "Har bäst chans att bli fotomodell?",
    "Är mest trolig att raka av sig håret?",
    "Är mest trolig att gifta sig och skaffa barn med någon man precis träffat?",
    "Är mest trolig att sova bort en hel dag?",
    "Är mest trolig att tappa bort sin telefon?",
    "Vill helst vara ett djur?",
    "Skulle kunna gå vilse i sin egen stad?",
    "Gråter mest?",
    "Önskar den var en influencer?",
    "Är mest sannolik att flirta med sin chef?",
    "Är klumpigast?",
    "Har skevast åsikter?",
    "Skulle kunna tatuera in sin partners namn?",
    "Har det mest städat hemma?",
    "Har det minst städat hemma?",
    "Ljuger mest?",
    "Ljuger minst?",
    "Ljuger sämst?",
    "Har haft den pinsammaste upplevelsen?",
    "Kan göra flest armhävningar? (bevisa det!)",
    "Är mest pålitlig?",
    "Är minst pålitlig?",
    "Skulle kunna gå i samma underkläder två dagar i rad?",
    "Är mest sannolik att hamna i fängelse?",
    "Skulle vara den bästa diktatorn?",
    "Skulle du ringa för hjälp i en krissituation?",
    "Skulle komma undan ett grovt brott?",
    "Skulle göra de sjukaste grejerna för pengar?",
    "Skulle kunna byta (eller har bytt!) kön?",
    "Har slösat mest pengar på en dag?",
    "Är snålast?",
    "Är girigast?",
    "Mest trolig att säga jag älskar dig för tidigt?",
    "Är mest romantisk?",
    "Är minst romantisk?",
    "Är mest grabbig?",
    "Är minst grabbig?",
    "Skulle kunna vara med någon bara för pengar?",
    "Har dejtat två personer samtidigt?",
    "Kommer gifta sig först?",
    "Kommer inte gifta sig?",
    "Har lättast att bli kär?",
    "Kommer hamna i skilsmässa?",
    "Kommer få flest barn?",
    "Skulle kunna ha en sugardaddy?",
];

export const PEKLEK_SPICY = [
    "Mest benägen att ha haft en one night stand?",
    "Skulle vilja byta kropp med för en dag p.g.a. sex appeal?",
    "Är ansedd som bäst i sängen i detta rum?",
    "Har troligast haft sex utomhus?",
    "Tros ha en hemlig samling sexleksaker?",
    "Skulle vilja se i en sexig outfit?",
    "Tros ha haft flest sexpartners?",
    "Ansedd som den vildaste i sängen?",
    "Mest trolig att ha haft en trekant?",
    "Skulle vilja ha en erotisk dröm om?",
    "Troligast att ha skickat nakenbilder?",
    "Skulle du välja för en het kyss?",
    "Tros ha haft en 'KK'?",
    "Har den sexigaste rösten?",
    "Ansedd som mest flirtig på fester?",
    "Troligen den mest intressanta erotiska dagboken?",
    "Skulle kunna vara undercover som strippa?",
    "Skulle kunna göra karriär som erotisk romanförfattare?",
    "Mest trolig att ha hemliga beundrare?",
    "Har den mest oemotståndliga charm?",
    "Misstänkt för att ha en fetisch ingen vet om?",
    "Skulle kunna hålla på en sexig hemlighet?",
    "Troligast att prova erotiska spel?",
    "Skulle kunna vara en mästare på förförelse?",
    "Skulle kunna ha en hemlig kärleksaffär?",
    "Mest sannolikt haft ett förhållande med en kändis?",
    "Mest benägen att kyssa och berätta?",
    "Skulle kunna skriva en sexkrönika?",
    "Sannolikt de mest spännande sexhistorierna?",
    "Troligast att smyga på första dejten?",
    "Skulle kunna vara den perfekta dominatrix?",
    "Har den mest förföriska dansen?",
    "Mest benägen att gå på blinddate?",
    "Bäst på att hålla sitt kärleksliv hemligt?",
    "Troligast att bli upptäckt med att vara otrogen?",
    "Mest sannolikt en hemlig kärleksrelation?",
    "Skulle vara en naturlig på en erotisk filmset?",
    "Skulle kunna leda en sexuell hälsoworkshop?",
    "Har den mest provocerande klädstilen?",
    "Skulle kunna skapa den hetaste datingprofilen?",
    "Tros njuta mest av erotisk litteratur?",
    "Skulle kunna vara framgångsrik som telefonsexoperatör?",
    "Troligast att vara öppen för en öppen relation?",
    "Skulle kunna vara mest innovativ i sovrummet?",
    "Mest sannolikt en hemlig porr-samling?",
    "Tros vara den största romantikern?",
    "Skulle kunna hålla den längsta förspelsessionen?",
    "Mest benägen att testa exotiska sexställningar?",
    "Har den mest dristiga fantasin?",
    "Tänker mest på sex?",
    "Förlorade oskulden först?",
    "Går naken hemma oftast?",
    "Har haft en könssjukdom?",
    "Har haft flest sexpartners?",
    "Har aldrig tagit en nakenbild?",
    "Har tagit flest nakenbilder?",
    "Skulle inte våga visa sin sökhistorik?",
    "Är mest lösaktig?",
    "Äger flest sexleksaker?",
    "Är bäst i sängen?",
    "Har haft flest one-night-stands?",
    "Mest trolig att säga fel namn under akten?",
    "Skulle skicka nudes utan att blinka?",
    "Skulle ha en crush på den mest otippade läraren? (Även flera år senare!)",
    "Skulle ragga med en usel raggningsreplik... och lyckas?",
    "Skulle ha ett regelbundet KK och hantera det utan känslor?",
    "Skulle testa en helt akrobatisk ställning från Kama Sutra?",
    "Skulle improvisera en striptease (även bara på skoj)?",
    "Skulle ha den mest imponerande (eller konstigaste) samlingen sexleksaker?",
    "Skulle skaffa en dejtingapp bara för att hitta ett one-night stand?",
    "Skulle i hemlighet fantisera om någon i det här rummet?",
    "Skulle redan ha blivit påkommen mitt i akten?",
    "Skulle föra en 'ligglista'?",
    "Skulle våga föreslå (eller tacka ja till) en trekant?",
    "Skulle titta på porr helt öppet?",
    "Skulle ha den mest pinsamma sexrelaterade historien?",
    "Skulle bli kär efter en enda het natt?",
    "Skulle redan ha överdrivit sina prestationer i sängen?",
    "Skulle säga att de föredrar förspel framför samlag?",
    "Skulle klara sig längst utan sex... och bli superirriterad?",
    "Skulle ha en väldigt specifik och lite oväntad 'typ'?",
    "Skulle skicka snuskiga meddelanden under ett jobbmöte (eller en lektion)?",
    "Skulle falla för någon som är mycket äldre (eller mycket yngre)?",
    "Skulle redan ha använt accessoarer som handbojor eller ögonbindel?",
    "Skulle vara högljuddast under sex?",
    "Skulle ha en riktigt snuskig hemlighet?",
    "Skulle gilla att bli dominerad (eller tvärtom, dominera) i sängen?",
    "Skulle ha haft en homosexuell upplevelse bara av nyfikenhet?",
    "Skulle ha en tatuering eller en piercing på ett väldigt... dolt ställe?",
    "Skulle skamlöst erkänna att man har fejkat en orgasm?",
    "Skulle ha haft flest olika sexpartners?",
    "Skulle våga föreslå en snuskig lek offentligt?",
    "Skulle ha haft sex på en ovanlig offentlig plats?",
    "Skulle ha en fantasi som involverar en uniform?",
    "Skulle vara bäst på sensuell massage?",
    "Skulle ha haft en helt virtuell relation?",
    "Skulle ha mest snuskigt skvaller om de andra i gruppen?",
    "Skulle gilla att bli fotad eller filmad under akten?",
    "Skulle ha ljugit om sitt antal partners?",
    "Skulle vara mest bekväm med att prata öppet om sex?",
    "Skulle ha ett 'safe word'?",
    "Skulle ha haft en könssjukdom (och prata öppet om det för att förebygga)?",
    "Skulle föredra en snabb och intensiv omgång framför en lång och sensuell?",
    "Skulle ha varit på en swingersklubb (eller skulle vilja testa)?",
    "Skulle ha ett altare tillägnat ett ex?",
    "Skulle gilla lätta bett eller rivmärken under sex?",
    "Skulle ha skrivit eller läst erotiska fanfictions?",
    "Skulle ha flest sexiga underkläder?",
    "Skulle ha stött på sin ex's bästa vän?",
    "Skulle mest troligt skrika fel namn vid fel tillfälle?",
    "Skulle ha en 'typ' baserad enbart på en kroppsdel?",
    "Skulle ha betalat för sex (eller övervägt att göra det)?",
];
