const PlayerQuestions = [
  "Favorite food",
  "Fav movie of all time?",
  "Ever had a ghost experience?",
  "Dream vacay spot?",
  "Cats or dogs?",
  "Most embarrassing thing you've done?",
  "Ever ghosted someone?",
  "Biggest guilty pleasure?",
  "Got any weird habits?",
  "Believe in soulmates?",
  "Weirdest food combo you love?",
  "Ever sent a risky text and regretted it?",
  "Most illegal thing you've done?",
  "Worst drunk moment?",
  "Ever had a crush on a teacher?",
  "Most used word when texting?",
  "Ever been caught in a lie?",
  "Weirdest dream you've had?",
  "Sleep with clothes on or nah?",
  "Ever been skinny dipping?",
  "Ever faked being sick to get out of something?",
  "Biggest lie you've told?",
  "Ever kissed someone you shouldn't have?",
  "Most random thing you've googled?",
  "Last thing you searched on your phone?",
  "Ever slid into someone's DMs?",
  "Ever had a crush on a friend's partner?",
  "Last time you went on a date?",
  "Ever been in love?",
  "Would you rather be rich or famous?",
  "Ever sent a text to the wrong player?",
  "Worst pickup line you've heard?",
  "Ever been caught doing something naughty?",
  "Ever been walked in on?",
  "Craziest place you've done it?",
  "Ever had a one-night stand?",
  "Biggest turn-on?",
  "Biggest turn-off?",
  "Ever been handcuffed?",
  "Lights on or off?",
  "Ever made out with a stranger?",
  "Ever hooked up with an ex?",
  "Thoughts on open relationships?",
  "Ever done it in public?",
  "Spit or swallow?",
  "Do you like dirty talk?",
  "Ever faked it?",
  "Best compliment you've ever gotten?",
  "Most attractive thing about someone?",
  "Would you rather cuddle or make out?",
  "What's something you find weirdly attractive?",
  "Ever had a friends-with-benefits situation?",
  "Ever been tied up?",
  "Ever played truth or dare and regretted it?",
  "Ever had a crush on a co-worker?",
  "Have a type or just go with vibes?",
  "Ever been in a love triangle?",
  "Ever been dumped in a brutal way?",
  "Ever dumped someone in a brutal way?",
  "Ever had a crazy ex?",
  "Ever had a dream about someone and it changed how you saw them?",
  "Ever had a crush on someone much older?",
  "Ever had a crush on a celeb that was kinda embarrassing?",
  "What's the most random thing that turns you on?",
  "Would you rather have amazing sex once or okay sex forever?",
  "Ever played strip poker?",
  "Ever sent a nude?",
  "Ever gotten a nude you didn't ask for?",
  "What's the weirdest place you've kissed someone?",
  "What's a secret you're keeping from everyone?",
  "Ever had a crush on someone off-limits?",
  "Ever been caught looking at something you shouldn't have?",
  "Ever lied about your body count?",
  "Would you rather be dominated or in control?",
  "Ever had a sex dream about a friend?",
  "Ever had a near-miss with getting caught?",
  "Ever made out with two different people in the same night?",
  "Ever faked being into something just to impress someone?",
  "Ever said 'I love you' and regretted it?",
  "Biggest regret in dating?",
  "Ever gone back to an ex?",
  "Ever been in a situation-ship that got messy?",
  "Do you think exes can be friends?",
  "Ever cheated or been cheated on?",
  "Would you rather a partner be too jealous or not care at all?",
  "What's the worst thing someone's called you in an argument?",
  "Ever been in a long-distance thing?",
  "Ever fallen for someone who was taken?",
  "Ever flirted with someone just for fun, not because you liked them?",
  "Biggest red flag in someone?",
  "Biggest green flag?",
  "What's something you wish people knew about you?",
  "Ever had a random hookup turn into something serious?",
  "What's something you'd never admit in real life but don't mind texting?",
  "Ever had a moment where you knew you messed up big time?",
  "Ever had someone ruin your whole mood with one text?",
  "Ever been called out in public for something embarrassing?",
  "Ever done something petty just to get back at someone?",
  "Ever gotten caught talking bad about someone?",
  "Ever had a moment where you just wanted the ground to swallow you?",
  "Ever gotten into a huge argument over something dumb?",
  "Ever seen a text that made your stomach drop?",
  "Ever been in a situation where you couldn't stop laughing but had to?",
];

const GroupQuestions = [
  "Everyone say their fav food, no repeats",
  "Movie you could rewatch forever?",
  "Ever had a ghost experience? Spill it",
  "Describe your dream vacay in 3 words",
  "Cats or dogs, no explaining",
  "Most embarrassing thing you've done, go",
  "Ever ghosted someone? Be honest",
  "Guilty pleasure you wouldn't admit on a first date?",
  "Name a weird habit you have",
  "Believe in soulmates? Quick yes or no",
  "Say a weird food combo you actually like",
  "Ever sent a risky text and instantly regretted it?",
  "Most illegal thing you've done (no judgment… maybe)",
  "Worst drunk moment? Everyone shares",
  "Ever had a crush on a teacher?",
  "Most used word when texting?",
  "Ever been caught in a lie?",
  "Weirdest dream you've had?",
  "Sleep with clothes on or nah?",
  "Ever skinny dipped?",
  "Ever faked being sick to get out of something?",
  "Biggest lie you've told?",
  "Ever kissed someone you shouldn't have?",
  "Most random thing you've googled?",
  "Last thing you searched on your phone?",
  "Ever slid into someone's DMs?",
  "Ever had a crush on a friend’s partner?",
  "Last time you went on a date?",
  "Ever been in love?",
  "Rather be rich or famous?",
  "Ever sent a text to the wrong player?",
  "Worst pickup line you’ve heard?",
  "Ever been caught doing something you shouldn’t?",
  "Ever been walked in on?",
  "Craziest place you've done it?",
  "Ever had a one-night stand?",
  "Biggest turn-on?",
  "Biggest turn-off?",
  "Ever been handcuffed?",
  "Lights on or off?",
  "Ever made out with a stranger?",
  "Ever hooked up with an ex?",
  "Thoughts on open relationships?",
  "Ever done it in public?",
  "Spit or swallow?",
  "Do you like dirty talk?",
  "Ever faked it?",
  "Best compliment you've ever gotten?",
  "Most attractive thing about someone?",
  "Cuddle or make out?",
  "What’s something weirdly attractive?",
  "Ever had a FWB situation?",
  "Ever been tied up?",
  "Ever played truth or dare and instantly regretted it?",
  "Ever had a crush on a co-worker?",
  "Got a type or just go with vibes?",
  "Ever been in a love triangle?",
  "Ever been dumped in a brutal way?",
  "Ever dumped someone in a brutal way?",
  "Ever had a crazy ex?",
  "Ever had a dream about someone that changed how you saw them?",
  "Ever had a crush on someone way older?",
  "Ever crushed on a celeb that’s kinda embarrassing?",
  "What’s the most random thing that turns you on?",
  "Rather have amazing sex once or okay sex forever?",
  "Ever played strip poker?",
  "Ever sent a nude?",
  "Ever gotten a nude you didn’t ask for?",
  "Weirdest place you’ve kissed someone?",
  "What’s a secret no one here knows?",
  "Ever crushed on someone off-limits?",
  "Ever been caught looking at something you shouldn't have?",
  "Ever lied about your body count?",
  "Rather be dominated or in control?",
  "Ever had a sex dream about someone in this group?",
  "Ever almost been caught doing something risky?",
  "Ever made out with two different people in one night?",
  "Ever faked being into something just to impress someone?",
  "Ever said ‘I love you’ and regretted it?",
  "Biggest dating regret?",
  "Ever gone back to an ex?",
  "Ever been in a situation-ship that got messy?",
  "Think exes can be friends?",
  "Ever cheated or been cheated on?",
  "Rather have a jealous partner or one that doesn’t care at all?",
  "Worst thing someone’s called you in an argument?",
  "Ever been in a long-distance thing?",
  "Ever fallen for someone who was taken?",
  "Ever flirted with someone just for fun, not bc you liked them?",
  "Biggest red flag in someone?",
  "Biggest green flag?",
  "Something you wish people knew about you?",
  "Ever had a random hookup turn into something serious?",
  "What’s something you'd never admit in real life but don’t mind saying here?",
  "Ever had a moment where you knew you messed up big time?",
  "Ever had someone ruin your whole mood with one text?",
  "Ever been called out in public for something embarrassing?",
  "Ever done something petty just to get back at someone?",
  "Ever gotten caught talking sh*t about someone?",
  "Ever had a moment where you just wanted the ground to swallow you?",
  "Ever gotten into a huge argument over something dumb?",
  "Ever seen a text that made your stomach drop?",
  "Ever been in a situation where you couldn’t stop laughing but had to?",
];

const PlayerChallenges = [
  "Send a risky text to the last player you texted",
  "Read the last message you sent out loud",
  "Take a sip if you’ve ever lied to get out of plans",
  "Say your biggest guilty pleasure",
  "Go to your camera roll and show the third most recent photo",
  "Scroll through your contacts and call the first player whose name starts with ‘J’",
  "Do an impression of someone in the room",
  "Try to lick your elbow",
  "Say one fun fact about yourself that no one here knows",
  "Let someone go through your phone for 30 seconds",
  "Send a random emoji to the first player on your Snapchat list",
  "Describe your dream partner in three words",
  "Let the player next to you pick a word and you have to freestyle rap with it",
  "Read the last DM you received out loud",
  "Let someone in the group change your profile picture to whatever they want for 10 minutes",
  "Go outside and yell ‘I love [your celeb crush]’",
  "Close your eyes and let someone hand you something random to eat",
  "Show the group your most used emoji",
  "Say the first word that comes to your mind right now",
  "Say something you’ve done that would shock your parents",
  "Take a selfie right now and send it to the 5th player in your recent texts",
  "Let someone pick a number between 1-10, and you have to take that many sips of your drink",
  "Let the group ask you one deep question, and you have to answer honestly",
  "Go through your search history and read out the last thing you searched",
  "Let someone else reply to a text on your phone",
  "Try to say the alphabet backwards as fast as you can",
  "Take a sip if you’ve ever sent a message and immediately regretted it",
  "Tell the group about your most awkward date",
  "Let someone in the group give you a new nickname for the night",
  "Describe your most embarrassing moment in detail",
  "Say something flirty to the player on your left",
  "Take off one accessory or piece of clothing",
  "Do 10 squats while looking someone in the eye",
  "Try to keep a straight face while the group tries to make you laugh",
  "Sing a line from a song that describes your love life",
  "Let someone read a random text on your phone",
  "Say the last thing you took a screenshot of",
  "Let someone make a tweet from your phone (you can delete after 10 min)",
  "Try to do a handstand or a cartwheel",
  "Show the group the weirdest app you have on your phone",
  "Let someone else set your phone wallpaper",
  "Do an impression of your crush",
  "Say something you would never admit to your parents",
  "Describe your type without saying any physical traits",
  "Let someone scroll through your playlist and pick a song for you to sing",
  "Give yourself a new name for the night and introduce yourself with it",
  "Let someone write a message on your forehead with a marker",
  "Let the group ask you anything, and you have to answer honestly",
  "Try to make the group laugh without using words",
  "Tell the group about your worst fashion choice ever",
  "Close your eyes and let someone feed you something random",
  "Read your last three texts out loud",
  "Let someone else DM your crush from your phone",
  "Take a selfie doing your best ‘model pose’ and send it to a random contact",
  "Let the player next to you choose a new name for your phone’s contact in their phone",
  "Say something you’ve never told anyone here",
  "Try to touch your toes without bending your knees",
  "Let someone pick a filter, and you have to post a selfie with it",
  "Describe your last dream in full detail",
  "Do an awkward dance for 10 seconds",
  "Close your eyes, and someone will hand you an object—you have to guess what it is",
  "Let the group decide on a new profile picture for your social media",
  "Say the first thing that comes to mind when you hear the word ‘love’",
  "Let someone else take a picture with your phone and post it on your story",
  "Try to do your best celebrity impression",
  "Describe the last time you felt really embarrassed",
  "Take a sip if you’ve ever sent a risky text",
  "Name one player in the group you’d date if you had to",
  "Tell a story about your most awkward moment ever",
  "Let someone write something on your hand with a marker",
  "Act out your favorite emoji without saying what it is",
  "Try to balance something on your head for 10 seconds",
  "Let someone go through your most recent photos and pick one to show the group",
  "Admit one thing you’ve been lying about lately",
  "Send a text to your mom or dad saying ‘We need to talk’ and don’t reply for 10 min",
  "Try to make an animal noise and see if the group can guess what it is",
  "Tell the group your worst habit",
  "Try to drink a full glass of water in one go",
  "Give a compliment to everyone in the room",
  "Say the last thing you liked on Instagram",
  "Post the last photo in your gallery to your story without explanation",
  "Whisper something to the player next to you and they have to say it out loud",
  "Try to say something seductive in the least seductive way possible",
  "Close your eyes and let someone take a random picture with your phone",
  "Let someone else choose a song, and you have to dance to it for 30 sec",
  "Admit the last thing you cried about",
  "Act out a scene from your favorite movie and see if the group can guess",
  "Let someone else in the group send an emoji to the last player you texted",
  "Do your best fake cry",
  "Pick someone in the group and say three nice things about them",
  "Show the group the last picture you took but don’t explain it",
  "Try to make an angry face without laughing",
  "Take a sip if you’ve ever texted an ex while drunk",
  "Say the last compliment someone gave you",
  "Describe your current mood using only one word",
  "Say the most random fact you know",
  "Sing the chorus of the first song that pops into your head",
  "Try to guess what the player to your left is thinking",
  "Let someone write a funny caption on your latest social media post",
  "Try to do the splits (or at least attempt it)",
  "Do your best impression of a cartoon character",
  "Say the last text message you received without giving any context",
  "Pick someone in the group and say something super nice about them",
  "Admit something that makes you cringe about yourself",
  "Do a slow-motion dramatic fall",
  "Act out an emotion without speaking, and let the group guess what it is",
  "Let someone take your phone and play any song, you have to dance to it",
  "Try to make everyone in the room smile in under 30 seconds",
];

const GroupChallenges = [
  "Everyone say their most used emoji, no repeats",
  "Go around and each player says their weirdest food combo",
  "Last player to touch their nose has to do 10 jumping jacks",
  "Everyone pick one player and say something nice about them",
  "Group votes on one player to send a random message to their last text",
  "Everyone take a sip if they’ve ever stalked an ex online",
  "Whoever has the lowest battery has to do a dare",
  "First player to laugh has to do an embarrassing dance",
  "Pick a word, and each player has to come up with a song lyric that has it",
  "Everyone show the last pic they took on their phone",
  "Everyone type a random emoji in the chat, no explaining",
  "Whoever has the most unread messages has to tell the group a secret",
  "Last player to say ‘not me’ has to do a TikTok dance",
  "Each player take turns saying a fun fact about themselves",
  "Everyone go to their camera roll and show the weirdest pic they find",
  "Everyone say their dream job but make it sound dramatic",
  "Go around and say the last thing you Googled",
  "Whoever got out of bed last today has to do 5 push-ups",
  "First player to blink in a staring contest has to tell a childhood story",
  "Everyone text the first contact under ‘J’ on their phone and say ‘hey’",
  "Whoever has the oldest unread text has to read it out loud",
  "Everyone show their most used app right now",
  "Each player say a random word, and the next player has to rhyme it",
  "Whoever has the most tabs open on their phone has to take a sip",
  "First player to check their phone has to do 20 squats",
  "Whoever’s birthday is closest has to sing a song chosen by the group",
  "Everyone go to their playlist and shuffle, then share the first song",
  "First player to yawn has to do a silly dance",
  "Whoever has the messiest room right now has to take a dare",
  "Each player share the cringiest thing they’ve ever posted online",
  "Everyone pick a random fact they know and say it",
  "Whoever is wearing the brightest color has to do 10 jumping jacks",
  "Everyone say the last movie they watched",
  "Whoever’s last name is first in alphabetical order has to share an embarrassing moment",
  "Each player has to say one thing they’re bad at",
  "Everyone say their first ever email address (if you dare)",
  "First player to touch their phone has to send a random emoji to their crush",
  "Whoever can hold their breath the longest gets to dare someone else",
  "Each player say a word that describes the player to their right",
  "Whoever has the most unread emails has to tell the group a lie and a truth",
  "Everyone send their first Instagram DM to a random player in their contacts",
  "Whoever has the shortest nails has to do a silly impression",
  "Each player says one thing they’d do if they won the lottery",
  "Whoever has the best poker face gets to make a new rule for the game",
  "Everyone take a sip if they’ve ever sent a text and regretted it",
  "Whoever’s last online order was the weirdest has to explain it",
  "Go around and everyone say the worst excuse they’ve used to cancel plans",
  "Whoever has the highest screen time today has to do a challenge",
  "Each player say one thing they would never do (but kinda wanna)",
  "Everyone turn their phones upside down, last player to do it takes a dare",
  "Whoever woke up the earliest today picks someone to do a challenge",
  "Everyone say something weird they believed as a kid",
  "Whoever has the oldest profile pic has to show it to the group",
  "First player to sneeze gets to pick a new rule for the next round",
  "Go around and each player say a funny WiFi name they’ve seen",
  "Everyone show their phone’s lock screen",
  "Whoever last took a mirror selfie has to recreate it now",
  "Whoever’s wearing the most black has to do their best animal impression",
  "Each player say one word to describe their day",
  "First player to check a notification has to post a random status update",
  "Whoever still remembers their childhood crush has to spill their name",
  "Everyone text the first contact in their phone ‘Guess what’ and see who replies first",
  "Whoever has the most alarms set on their phone has to take a dare",
  "Go around and say a movie or show you refuse to watch",
  "Whoever has the most unread notifications has to send a text to their mom saying ‘what’s up’",
  "Everyone go to their messages and read the last thing they sent",
  "Whoever has the best dramatic voice gets to do a mini speech about something random",
  "Each player has to say their most used emoji without showing it",
  "Whoever is the tallest in the group has to tell an embarrassing story",
  "First player to yawn has to compliment everyone in the group",
  "Whoever’s name has the most letters has to share a random secret",
  "Everyone go to their recent emojis and use the first three in a sentence",
  "Whoever got the most sleep last night has to do an impression of their celeb crush",
  "Whoever had coffee today has to do a silly challenge chosen by the group",
  "First player to say ‘I don’t know’ has to sing a random song",
  "Whoever is sitting closest to the door has to dance for 10 seconds",
  "Everyone say one word that describes their current mood",
  "Whoever ate the most junk food today has to tell an embarrassing childhood memory",
  "First player to say ‘what’ has to do an accent challenge",
  "Whoever has the oldest unread text has to read it out loud",
  "Everyone check their screen time and say what app they’ve used the most today",
  "Whoever’s birthday is next has to take a dare",
  "Everyone say the first thing they’d buy if they won the lottery",
  "Whoever can make the best dramatic slow-motion fall wins and can pick a challenge for someone else",
  "Whoever can hold a plank the longest gets to make a rule for the next round",
  "Go around and say your weirdest fear",
  "Whoever has the most random app on their phone has to show it to the group",
  "First player to blink in a staring contest has to take a sip",
  "Whoever has the best fake cry wins a free pass for the next challenge",
  "Whoever is the worst at keeping secrets has to prove they can keep one by hearing one from someone else",
  "Whoever has been to the most countries has to share their best travel story",
  "Whoever has the longest name has to make up a 10-second freestyle rap",
  "Whoever is the best at impressions has to do one now",
  "First player to laugh has to do a dare chosen by the group",
  "Whoever has the most exes has to tell a dating horror story",
  "First player to check their phone has to hand it over to someone else for the next round",
  "Whoever has the messiest room right now has to take a picture and send it to the group chat",
  "Everyone pick a song they love but are lowkey embarrassed about and share it",
  "Whoever can make the best animal noise gets to skip the next round",
  "Whoever can balance on one foot the longest wins and can pick someone to do a dare",
  "Everyone say their last dream in one sentence",
  "Whoever has the oldest meme saved in their phone has to show it",
  "Whoever’s name has the most vowels has to make up a haiku on the spot",
];

export const TruthStatements = [
  "Got kicked out of a place once",
  "Can fall asleep anywhere, anytime",
  "Ate a whole cake alone",
  "Sent a text n regretted it instantly",
  "Met a celeb, had no idea who it was",
  "Been in an ambulance but wasn’t hurt",
  "Stayed up 48+ hrs straight",
  "Accidentally stole something from a store",
  "Texted an ex when shouldn't have",
  "Got lost in my own city",
  "Laughed so hard snorted in public",
  "Caught doing something super embarrassing",
  "Pretended to be sick to skip something big",
  "Tripped n fell in front of a huge crowd",
  "Told I talk in my sleep",
  "Weird celeb crush, no regrets",
  "Ate something off the floor n didn’t care",
  "Used a fake name at Starbucks just for fun",
  "Sent a risky text n put phone on airplane mode",
  "Went a whole day without checking my phone",
  "Got stuck in an elevator before",
  "Laughed so hard spit my drink everywhere",
  "Accidentally called teacher ‘mom’",
  "Fell asleep mid-text",
  "Walked into a glass door thinking it was open",
  "Phone smacked my face while texting in bed",
  "Kept a secret for someone for years",
  "Ate something found in my car",
  "Forgot my own bday once",
  "Been in a group chat where they talked bad about me",
  "Had a dream so weird never told anyone",
  "Rewatched a show so many times know all the lines",
  "Texted the wrong player something embarrassing",
  "Faked knowing a song in a convo",
  "Waved back at someone who wasn’t waving at me",
  "Used the wrong name for someone n didn't realize",
  "Got lost walking in a mall",
  "Seen someone wave at me n just ignored it hoping they weren’t",
  "Faked laughing at a joke didn’t get at all",
  "Pretended to understand a convo n had no clue",
  "Got called out for staring at someone by accident",
  "Said ‘you too’ when waiter said enjoy your meal",
  "Lost my phone while holding it in my hand",
  "Pretended to text just to avoid talking to someone",
  "Accidentally liked a post while deep stalking",
  "Said a joke so bad got dead silence",
  "Got caught taking a selfie",
  "Fell asleep in a public place",
  "Ordered food n totally forgot about it",
  "Tried to whisper but it was way too loud",
  "Held the door open for someone n they walked the other way",
  "Saw someone running so started running too for no reason",
  "Sent a risky text n immediately panicked",
  "Said ‘you too’ when someone told me happy birthday",
  "Missed a turn while driving n just pretended it was on purpose",
  "Had a convo with someone n realized later I misheard everything",
  "Tried to make a joke but it sounded way meaner than I meant",
  "Started typing a message n never sent it",
  "Typed ‘haha’ but wasn’t even smiling",
  "Tried to sneak a pic of someone n flash went off",
  "Tried to be cool n tripped immediately after",
  "Used the wrong emoji in a serious convo",
  "Lied about liking a movie just to fit in",
  "Stared at my phone so long forgot what I was gonna do",
  "Texted ‘on my way’ when I was still in bed",
  "Pretended to get a call just to leave a convo",
  "Typed out a whole message n just deleted it instead",
  "Held in a sneeze n made the weirdest noise instead",
  "Opened a message, forgot to reply for days",
  "Sent a voice note n immediately cringed at my own voice",
  "Accidentally texted something meant for someone else",
  "Made up a fake excuse to leave early",
  "Felt my phone vibrate but it didn’t",
  "Said ‘bye love you’ on accident to the wrong player",
  "Spilled something in public n pretended it wasn’t me",
  "Tried to take a cool pic but fell instead",
  "Used my phone as a flashlight n lost it while holding it",
  "Saw someone waving so I waved back but it wasn’t for me",
  "Pretended to know what someone was talking about n had no idea",
  "Made an excuse to not go out but got caught outside anyway",
  "Ran into someone I was ignoring n had to act normal",
  "Started telling a story n realized halfway it wasn’t funny",
  "Sent a text n instantly put my phone face down",
  "Accidentally sent ‘haha’ to something not funny at all",
  "Tried to take a sip of my drink n totally missed my mouth",
  "Tripped over nothing while walking alone",
  "Made an ugly face thinking camera was off but it wasn’t",
  "Held the door for someone too early so it was awkward",
  "Messed up a handshake n just walked away",
  "Said something under my breath n realized they heard me",
  "Laughed at something n immediately regretted it",
  "Forgot what day it was n acted like I knew",
  "Sent a risky text n put phone on airplane mode",
  "Stared at someone by accident n made it weird",
  "Said ‘you too’ to something that made no sense",
  "Tried to delete a message but they already saw it",
  "Fell asleep in the middle of typing a text",
  "Pretended not to hear someone calling my name",
  "Saw a typo after sending n hoped no one noticed",
  "Meant to screenshot something n accidentally locked my phone",
  "Tried to act like I knew the lyrics but mumbled through most of it",
  "Replied ‘lol’ but wasn’t even smiling",
  "Made eye contact with someone while yawning n it was awkward",
  "Walked into a room n immediately forgot why",
  "Pretended to be busy on my phone to avoid talking",
  "Got lost following GPS",
  "Had someone call me out for using the wrong name n played it off",
  "Typed a long text n just deleted it instead of sending",
];
export const LieStatements = [
  "Can do a backflip",
  "Never eaten fast food",
  "Speak 5 languages fluently",
  "Never broken a single rule",
  "Met a celeb and they asked for my autograph",
  "Never sent a risky text",
  "Can run a mile in under 5 mins",
  "Once won a huge lottery prize",
  "Hate chocolate",
  "Never stayed up past midnight",
  "Was on a reality TV show",
  "Have never been late to anything",
  "Can juggle 4 things at once",
  "Never skipped a class in my life",
  "Have never spilled a drink on myself",
  "Can hold my breath for 3 minutes",
  "Never laughed at an inappropriate moment",
  "Have a twin nobody knows about",
  "Was prom king/queen",
  "Never dropped my phone in water",
  "Can type 200 words per minute",
  "Have never forgotten my own birthday",
  "Once met the president",
  "Can do 50 push-ups without stopping",
  "Have never been scared of the dark",
  "Never lost a single game of rock-paper-scissors",
  "Once wrestled an alligator",
  "Have a pet snake",
  "Never used a fake name at Starbucks",
  "Have been in a Hollywood movie",
  "Hate pizza",
  "Once got a tattoo on a dare",
  "Have a million followers on TikTok",
  "Can whistle with my fingers",
  "Never lied in my life",
  "Was in a viral YouTube video",
  "Can solve a Rubik's cube in under a minute",
  "Never sent a text I regretted",
  "Have never cried during a movie",
  "Can do the splits",
  "Have never forgotten someone’s name mid-convo",
  "Never been caught in a lie",
  "Can play 3 musical instruments",
  "Never had a celebrity crush",
  "Once rode a dolphin",
  "Have a hidden tattoo",
  "Have never tripped in public",
  "Never pressed ‘send’ on a message too early",
  "Once won a hotdog eating contest",
  "Have met someone with the same first and last name as me",
  "Can draw a perfect circle freehand",
  "Never lost a bet",
  "Have never been embarrassed",
  "Can do 10 pull-ups in a row",
  "Never had a dream so weird I was scared to tell anyone",
  "Can do a perfect British accent",
  "Have never forgotten my phone somewhere",
  "Can write with both hands",
  "Once saved someone’s life",
  "Have never googled myself",
  "Never got a song stuck in my head for days",
  "Can rap every word to a song perfectly",
  "Once climbed a mountain",
  "Never had a crush on someone in this group",
  "Once won a national competition",
  "Never fallen asleep during a movie",
  "Have a secret hidden talent",
  "Can name every capital city in the world",
  "Never messed up a handshake",
  "Once got mistaken for a celebrity",
  "Can drink a whole bottle of water in one go",
  "Have never dropped my phone on my face",
  "Can do a cartwheel perfectly",
  "Never got caught talking bad about someone",
  "Once had a pet monkey",
  "Have never sent a text to the wrong player",
  "Never forgotten a password",
  "Can eat a whole lemon without making a face",
  "Never sang along to a song and got the lyrics wrong",
  "Once went a week without checking my phone",
  "Can touch my toes without bending my knees",
  "Never screamed out loud at a horror movie",
  "Can balance a spoon on my nose",
  "Never laughed at something that wasn’t supposed to be funny",
  "Once stayed in a haunted house overnight",
  "Can do the worm dance move",
  "Never lost a sock in the laundry",
  "Have never faked being on the phone to avoid someone",
  "Never gotten lost in a mall",
  "Can make the best pancakes",
  "Never checked my phone mid-convo out of boredom",
  "Once won a dance-off",
  "Never dropped food on my clothes",
  "Once got away with something really bad",
  "Can spin a basketball on my finger",
  "Never spilled a drink on my laptop",
  "Once got a text from a famous player",
  "Never forgotten someone’s birthday",
  "Can lick my elbow",
  "Never hit ‘send’ on a message too early",
  "Once ate an entire jar of pickles in one sitting",
  "Can memorize a deck of cards",
  "Never took a nap and woke up thinking it was the next day",
  "Once finished a whole Netflix series in one day",
  "Can crack every single knuckle on command",
  "Never laughed at something when I wasn’t supposed to",
  "Can guess someone’s zodiac sign just by looking at them",
];

export const Help = {
  PlayerQuestions,
  GroupQuestions,
  PlayerChallenges,
  GroupChallenges,
  TruthStatements,
  LieStatements,
};
