/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LiveRouteRouteImport } from './routes/live/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LocalChallengeIndexRouteImport } from './routes/local/challenge/index'
import { Route as LiveAnonymousJoinRouteImport } from './routes/live/anonymous/join'
import { Route as LiveAnonymousCreateRouteImport } from './routes/live/anonymous/create'
import { Route as LiveAnonymousIdIndexRouteImport } from './routes/live/anonymous/$id/index'

const LiveRouteRoute = LiveRouteRouteImport.update({
  id: '/live',
  path: '/live',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LocalChallengeIndexRoute = LocalChallengeIndexRouteImport.update({
  id: '/local/challenge/',
  path: '/local/challenge/',
  getParentRoute: () => rootRouteImport,
} as any)
const LiveAnonymousJoinRoute = LiveAnonymousJoinRouteImport.update({
  id: '/anonymous/join',
  path: '/anonymous/join',
  getParentRoute: () => LiveRouteRoute,
} as any)
const LiveAnonymousCreateRoute = LiveAnonymousCreateRouteImport.update({
  id: '/anonymous/create',
  path: '/anonymous/create',
  getParentRoute: () => LiveRouteRoute,
} as any)
const LiveAnonymousIdIndexRoute = LiveAnonymousIdIndexRouteImport.update({
  id: '/anonymous/$id/',
  path: '/anonymous/$id/',
  getParentRoute: () => LiveRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/live': typeof LiveRouteRouteWithChildren
  '/live/anonymous/create': typeof LiveAnonymousCreateRoute
  '/live/anonymous/join': typeof LiveAnonymousJoinRoute
  '/local/challenge': typeof LocalChallengeIndexRoute
  '/live/anonymous/$id': typeof LiveAnonymousIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/live': typeof LiveRouteRouteWithChildren
  '/live/anonymous/create': typeof LiveAnonymousCreateRoute
  '/live/anonymous/join': typeof LiveAnonymousJoinRoute
  '/local/challenge': typeof LocalChallengeIndexRoute
  '/live/anonymous/$id': typeof LiveAnonymousIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/live': typeof LiveRouteRouteWithChildren
  '/live/anonymous/create': typeof LiveAnonymousCreateRoute
  '/live/anonymous/join': typeof LiveAnonymousJoinRoute
  '/local/challenge/': typeof LocalChallengeIndexRoute
  '/live/anonymous/$id/': typeof LiveAnonymousIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/live'
    | '/live/anonymous/create'
    | '/live/anonymous/join'
    | '/local/challenge'
    | '/live/anonymous/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/live'
    | '/live/anonymous/create'
    | '/live/anonymous/join'
    | '/local/challenge'
    | '/live/anonymous/$id'
  id:
    | '__root__'
    | '/'
    | '/live'
    | '/live/anonymous/create'
    | '/live/anonymous/join'
    | '/local/challenge/'
    | '/live/anonymous/$id/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LiveRouteRoute: typeof LiveRouteRouteWithChildren
  LocalChallengeIndexRoute: typeof LocalChallengeIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/live': {
      id: '/live'
      path: '/live'
      fullPath: '/live'
      preLoaderRoute: typeof LiveRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/local/challenge/': {
      id: '/local/challenge/'
      path: '/local/challenge'
      fullPath: '/local/challenge'
      preLoaderRoute: typeof LocalChallengeIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/live/anonymous/join': {
      id: '/live/anonymous/join'
      path: '/anonymous/join'
      fullPath: '/live/anonymous/join'
      preLoaderRoute: typeof LiveAnonymousJoinRouteImport
      parentRoute: typeof LiveRouteRoute
    }
    '/live/anonymous/create': {
      id: '/live/anonymous/create'
      path: '/anonymous/create'
      fullPath: '/live/anonymous/create'
      preLoaderRoute: typeof LiveAnonymousCreateRouteImport
      parentRoute: typeof LiveRouteRoute
    }
    '/live/anonymous/$id/': {
      id: '/live/anonymous/$id/'
      path: '/anonymous/$id'
      fullPath: '/live/anonymous/$id'
      preLoaderRoute: typeof LiveAnonymousIdIndexRouteImport
      parentRoute: typeof LiveRouteRoute
    }
  }
}

interface LiveRouteRouteChildren {
  LiveAnonymousCreateRoute: typeof LiveAnonymousCreateRoute
  LiveAnonymousJoinRoute: typeof LiveAnonymousJoinRoute
  LiveAnonymousIdIndexRoute: typeof LiveAnonymousIdIndexRoute
}

const LiveRouteRouteChildren: LiveRouteRouteChildren = {
  LiveAnonymousCreateRoute: LiveAnonymousCreateRoute,
  LiveAnonymousJoinRoute: LiveAnonymousJoinRoute,
  LiveAnonymousIdIndexRoute: LiveAnonymousIdIndexRoute,
}

const LiveRouteRouteWithChildren = LiveRouteRoute._addFileChildren(
  LiveRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LiveRouteRoute: LiveRouteRouteWithChildren,
  LocalChallengeIndexRoute: LocalChallengeIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
