/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LiveRouteRouteImport } from './routes/live/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LocalWaterfallIndexRouteImport } from './routes/local/waterfall/index'
import { Route as LocalSalenIndexRouteImport } from './routes/local/salen/index'
import { Route as LocalPeklekIndexRouteImport } from './routes/local/peklek/index'
import { Route as LocalChallengeIndexRouteImport } from './routes/local/challenge/index'
import { Route as LiveWhoisJoinRouteImport } from './routes/live/whois/join'
import { Route as LiveWhoisCreateRouteImport } from './routes/live/whois/create'
import { Route as LiveReactionTimeJoinRouteImport } from './routes/live/reaction-time/join'
import { Route as LiveReactionTimeCreateRouteImport } from './routes/live/reaction-time/create'
import { Route as LiveAnonymousJoinRouteImport } from './routes/live/anonymous/join'
import { Route as LiveAnonymousCreateRouteImport } from './routes/live/anonymous/create'
import { Route as LocalSalenIdIndexRouteImport } from './routes/local/salen/$id/index'
import { Route as LocalPeklekModeIndexRouteImport } from './routes/local/peklek/$mode/index'
import { Route as LiveWhoisIdIndexRouteImport } from './routes/live/whois/$id/index'
import { Route as LiveReactionTimeIdIndexRouteImport } from './routes/live/reaction-time/$id/index'
import { Route as LiveAnonymousIdIndexRouteImport } from './routes/live/anonymous/$id/index'

const LiveRouteRoute = LiveRouteRouteImport.update({
  id: '/live',
  path: '/live',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LocalWaterfallIndexRoute = LocalWaterfallIndexRouteImport.update({
  id: '/local/waterfall/',
  path: '/local/waterfall/',
  getParentRoute: () => rootRouteImport,
} as any)
const LocalSalenIndexRoute = LocalSalenIndexRouteImport.update({
  id: '/local/salen/',
  path: '/local/salen/',
  getParentRoute: () => rootRouteImport,
} as any)
const LocalPeklekIndexRoute = LocalPeklekIndexRouteImport.update({
  id: '/local/peklek/',
  path: '/local/peklek/',
  getParentRoute: () => rootRouteImport,
} as any)
const LocalChallengeIndexRoute = LocalChallengeIndexRouteImport.update({
  id: '/local/challenge/',
  path: '/local/challenge/',
  getParentRoute: () => rootRouteImport,
} as any)
const LiveWhoisJoinRoute = LiveWhoisJoinRouteImport.update({
  id: '/whois/join',
  path: '/whois/join',
  getParentRoute: () => LiveRouteRoute,
} as any)
const LiveWhoisCreateRoute = LiveWhoisCreateRouteImport.update({
  id: '/whois/create',
  path: '/whois/create',
  getParentRoute: () => LiveRouteRoute,
} as any)
const LiveReactionTimeJoinRoute = LiveReactionTimeJoinRouteImport.update({
  id: '/reaction-time/join',
  path: '/reaction-time/join',
  getParentRoute: () => LiveRouteRoute,
} as any)
const LiveReactionTimeCreateRoute = LiveReactionTimeCreateRouteImport.update({
  id: '/reaction-time/create',
  path: '/reaction-time/create',
  getParentRoute: () => LiveRouteRoute,
} as any)
const LiveAnonymousJoinRoute = LiveAnonymousJoinRouteImport.update({
  id: '/anonymous/join',
  path: '/anonymous/join',
  getParentRoute: () => LiveRouteRoute,
} as any)
const LiveAnonymousCreateRoute = LiveAnonymousCreateRouteImport.update({
  id: '/anonymous/create',
  path: '/anonymous/create',
  getParentRoute: () => LiveRouteRoute,
} as any)
const LocalSalenIdIndexRoute = LocalSalenIdIndexRouteImport.update({
  id: '/local/salen/$id/',
  path: '/local/salen/$id/',
  getParentRoute: () => rootRouteImport,
} as any)
const LocalPeklekModeIndexRoute = LocalPeklekModeIndexRouteImport.update({
  id: '/local/peklek/$mode/',
  path: '/local/peklek/$mode/',
  getParentRoute: () => rootRouteImport,
} as any)
const LiveWhoisIdIndexRoute = LiveWhoisIdIndexRouteImport.update({
  id: '/whois/$id/',
  path: '/whois/$id/',
  getParentRoute: () => LiveRouteRoute,
} as any)
const LiveReactionTimeIdIndexRoute = LiveReactionTimeIdIndexRouteImport.update({
  id: '/reaction-time/$id/',
  path: '/reaction-time/$id/',
  getParentRoute: () => LiveRouteRoute,
} as any)
const LiveAnonymousIdIndexRoute = LiveAnonymousIdIndexRouteImport.update({
  id: '/anonymous/$id/',
  path: '/anonymous/$id/',
  getParentRoute: () => LiveRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/live': typeof LiveRouteRouteWithChildren
  '/live/anonymous/create': typeof LiveAnonymousCreateRoute
  '/live/anonymous/join': typeof LiveAnonymousJoinRoute
  '/live/reaction-time/create': typeof LiveReactionTimeCreateRoute
  '/live/reaction-time/join': typeof LiveReactionTimeJoinRoute
  '/live/whois/create': typeof LiveWhoisCreateRoute
  '/live/whois/join': typeof LiveWhoisJoinRoute
  '/local/challenge': typeof LocalChallengeIndexRoute
  '/local/peklek': typeof LocalPeklekIndexRoute
  '/local/salen': typeof LocalSalenIndexRoute
  '/local/waterfall': typeof LocalWaterfallIndexRoute
  '/live/anonymous/$id': typeof LiveAnonymousIdIndexRoute
  '/live/reaction-time/$id': typeof LiveReactionTimeIdIndexRoute
  '/live/whois/$id': typeof LiveWhoisIdIndexRoute
  '/local/peklek/$mode': typeof LocalPeklekModeIndexRoute
  '/local/salen/$id': typeof LocalSalenIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/live': typeof LiveRouteRouteWithChildren
  '/live/anonymous/create': typeof LiveAnonymousCreateRoute
  '/live/anonymous/join': typeof LiveAnonymousJoinRoute
  '/live/reaction-time/create': typeof LiveReactionTimeCreateRoute
  '/live/reaction-time/join': typeof LiveReactionTimeJoinRoute
  '/live/whois/create': typeof LiveWhoisCreateRoute
  '/live/whois/join': typeof LiveWhoisJoinRoute
  '/local/challenge': typeof LocalChallengeIndexRoute
  '/local/peklek': typeof LocalPeklekIndexRoute
  '/local/salen': typeof LocalSalenIndexRoute
  '/local/waterfall': typeof LocalWaterfallIndexRoute
  '/live/anonymous/$id': typeof LiveAnonymousIdIndexRoute
  '/live/reaction-time/$id': typeof LiveReactionTimeIdIndexRoute
  '/live/whois/$id': typeof LiveWhoisIdIndexRoute
  '/local/peklek/$mode': typeof LocalPeklekModeIndexRoute
  '/local/salen/$id': typeof LocalSalenIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/live': typeof LiveRouteRouteWithChildren
  '/live/anonymous/create': typeof LiveAnonymousCreateRoute
  '/live/anonymous/join': typeof LiveAnonymousJoinRoute
  '/live/reaction-time/create': typeof LiveReactionTimeCreateRoute
  '/live/reaction-time/join': typeof LiveReactionTimeJoinRoute
  '/live/whois/create': typeof LiveWhoisCreateRoute
  '/live/whois/join': typeof LiveWhoisJoinRoute
  '/local/challenge/': typeof LocalChallengeIndexRoute
  '/local/peklek/': typeof LocalPeklekIndexRoute
  '/local/salen/': typeof LocalSalenIndexRoute
  '/local/waterfall/': typeof LocalWaterfallIndexRoute
  '/live/anonymous/$id/': typeof LiveAnonymousIdIndexRoute
  '/live/reaction-time/$id/': typeof LiveReactionTimeIdIndexRoute
  '/live/whois/$id/': typeof LiveWhoisIdIndexRoute
  '/local/peklek/$mode/': typeof LocalPeklekModeIndexRoute
  '/local/salen/$id/': typeof LocalSalenIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/live'
    | '/live/anonymous/create'
    | '/live/anonymous/join'
    | '/live/reaction-time/create'
    | '/live/reaction-time/join'
    | '/live/whois/create'
    | '/live/whois/join'
    | '/local/challenge'
    | '/local/peklek'
    | '/local/salen'
    | '/local/waterfall'
    | '/live/anonymous/$id'
    | '/live/reaction-time/$id'
    | '/live/whois/$id'
    | '/local/peklek/$mode'
    | '/local/salen/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/live'
    | '/live/anonymous/create'
    | '/live/anonymous/join'
    | '/live/reaction-time/create'
    | '/live/reaction-time/join'
    | '/live/whois/create'
    | '/live/whois/join'
    | '/local/challenge'
    | '/local/peklek'
    | '/local/salen'
    | '/local/waterfall'
    | '/live/anonymous/$id'
    | '/live/reaction-time/$id'
    | '/live/whois/$id'
    | '/local/peklek/$mode'
    | '/local/salen/$id'
  id:
    | '__root__'
    | '/'
    | '/live'
    | '/live/anonymous/create'
    | '/live/anonymous/join'
    | '/live/reaction-time/create'
    | '/live/reaction-time/join'
    | '/live/whois/create'
    | '/live/whois/join'
    | '/local/challenge/'
    | '/local/peklek/'
    | '/local/salen/'
    | '/local/waterfall/'
    | '/live/anonymous/$id/'
    | '/live/reaction-time/$id/'
    | '/live/whois/$id/'
    | '/local/peklek/$mode/'
    | '/local/salen/$id/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LiveRouteRoute: typeof LiveRouteRouteWithChildren
  LocalChallengeIndexRoute: typeof LocalChallengeIndexRoute
  LocalPeklekIndexRoute: typeof LocalPeklekIndexRoute
  LocalSalenIndexRoute: typeof LocalSalenIndexRoute
  LocalWaterfallIndexRoute: typeof LocalWaterfallIndexRoute
  LocalPeklekModeIndexRoute: typeof LocalPeklekModeIndexRoute
  LocalSalenIdIndexRoute: typeof LocalSalenIdIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/live': {
      id: '/live'
      path: '/live'
      fullPath: '/live'
      preLoaderRoute: typeof LiveRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/local/waterfall/': {
      id: '/local/waterfall/'
      path: '/local/waterfall'
      fullPath: '/local/waterfall'
      preLoaderRoute: typeof LocalWaterfallIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/local/salen/': {
      id: '/local/salen/'
      path: '/local/salen'
      fullPath: '/local/salen'
      preLoaderRoute: typeof LocalSalenIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/local/peklek/': {
      id: '/local/peklek/'
      path: '/local/peklek'
      fullPath: '/local/peklek'
      preLoaderRoute: typeof LocalPeklekIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/local/challenge/': {
      id: '/local/challenge/'
      path: '/local/challenge'
      fullPath: '/local/challenge'
      preLoaderRoute: typeof LocalChallengeIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/live/whois/join': {
      id: '/live/whois/join'
      path: '/whois/join'
      fullPath: '/live/whois/join'
      preLoaderRoute: typeof LiveWhoisJoinRouteImport
      parentRoute: typeof LiveRouteRoute
    }
    '/live/whois/create': {
      id: '/live/whois/create'
      path: '/whois/create'
      fullPath: '/live/whois/create'
      preLoaderRoute: typeof LiveWhoisCreateRouteImport
      parentRoute: typeof LiveRouteRoute
    }
    '/live/reaction-time/join': {
      id: '/live/reaction-time/join'
      path: '/reaction-time/join'
      fullPath: '/live/reaction-time/join'
      preLoaderRoute: typeof LiveReactionTimeJoinRouteImport
      parentRoute: typeof LiveRouteRoute
    }
    '/live/reaction-time/create': {
      id: '/live/reaction-time/create'
      path: '/reaction-time/create'
      fullPath: '/live/reaction-time/create'
      preLoaderRoute: typeof LiveReactionTimeCreateRouteImport
      parentRoute: typeof LiveRouteRoute
    }
    '/live/anonymous/join': {
      id: '/live/anonymous/join'
      path: '/anonymous/join'
      fullPath: '/live/anonymous/join'
      preLoaderRoute: typeof LiveAnonymousJoinRouteImport
      parentRoute: typeof LiveRouteRoute
    }
    '/live/anonymous/create': {
      id: '/live/anonymous/create'
      path: '/anonymous/create'
      fullPath: '/live/anonymous/create'
      preLoaderRoute: typeof LiveAnonymousCreateRouteImport
      parentRoute: typeof LiveRouteRoute
    }
    '/local/salen/$id/': {
      id: '/local/salen/$id/'
      path: '/local/salen/$id'
      fullPath: '/local/salen/$id'
      preLoaderRoute: typeof LocalSalenIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/local/peklek/$mode/': {
      id: '/local/peklek/$mode/'
      path: '/local/peklek/$mode'
      fullPath: '/local/peklek/$mode'
      preLoaderRoute: typeof LocalPeklekModeIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/live/whois/$id/': {
      id: '/live/whois/$id/'
      path: '/whois/$id'
      fullPath: '/live/whois/$id'
      preLoaderRoute: typeof LiveWhoisIdIndexRouteImport
      parentRoute: typeof LiveRouteRoute
    }
    '/live/reaction-time/$id/': {
      id: '/live/reaction-time/$id/'
      path: '/reaction-time/$id'
      fullPath: '/live/reaction-time/$id'
      preLoaderRoute: typeof LiveReactionTimeIdIndexRouteImport
      parentRoute: typeof LiveRouteRoute
    }
    '/live/anonymous/$id/': {
      id: '/live/anonymous/$id/'
      path: '/anonymous/$id'
      fullPath: '/live/anonymous/$id'
      preLoaderRoute: typeof LiveAnonymousIdIndexRouteImport
      parentRoute: typeof LiveRouteRoute
    }
  }
}

interface LiveRouteRouteChildren {
  LiveAnonymousCreateRoute: typeof LiveAnonymousCreateRoute
  LiveAnonymousJoinRoute: typeof LiveAnonymousJoinRoute
  LiveReactionTimeCreateRoute: typeof LiveReactionTimeCreateRoute
  LiveReactionTimeJoinRoute: typeof LiveReactionTimeJoinRoute
  LiveWhoisCreateRoute: typeof LiveWhoisCreateRoute
  LiveWhoisJoinRoute: typeof LiveWhoisJoinRoute
  LiveAnonymousIdIndexRoute: typeof LiveAnonymousIdIndexRoute
  LiveReactionTimeIdIndexRoute: typeof LiveReactionTimeIdIndexRoute
  LiveWhoisIdIndexRoute: typeof LiveWhoisIdIndexRoute
}

const LiveRouteRouteChildren: LiveRouteRouteChildren = {
  LiveAnonymousCreateRoute: LiveAnonymousCreateRoute,
  LiveAnonymousJoinRoute: LiveAnonymousJoinRoute,
  LiveReactionTimeCreateRoute: LiveReactionTimeCreateRoute,
  LiveReactionTimeJoinRoute: LiveReactionTimeJoinRoute,
  LiveWhoisCreateRoute: LiveWhoisCreateRoute,
  LiveWhoisJoinRoute: LiveWhoisJoinRoute,
  LiveAnonymousIdIndexRoute: LiveAnonymousIdIndexRoute,
  LiveReactionTimeIdIndexRoute: LiveReactionTimeIdIndexRoute,
  LiveWhoisIdIndexRoute: LiveWhoisIdIndexRoute,
}

const LiveRouteRouteWithChildren = LiveRouteRoute._addFileChildren(
  LiveRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LiveRouteRoute: LiveRouteRouteWithChildren,
  LocalChallengeIndexRoute: LocalChallengeIndexRoute,
  LocalPeklekIndexRoute: LocalPeklekIndexRoute,
  LocalSalenIndexRoute: LocalSalenIndexRoute,
  LocalWaterfallIndexRoute: LocalWaterfallIndexRoute,
  LocalPeklekModeIndexRoute: LocalPeklekModeIndexRoute,
  LocalSalenIdIndexRoute: LocalSalenIdIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
